---
- name: Install Ruby && Bundler
  hosts: all
  become: true
  tasks:
  # Установим в цикле все зависимости
  - name: Install ruby and rubygems and required packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - ruby-full
      - ruby-bundler
      - build-essential
